### ISSUE TITLE
JSchema.ToString() truncates dependencies belonging to a definition

### ISSUE THREAD

**Issue by anothercraig** [JamesNK/Newtonsoft.Json.Schema#191] opened 2019-08-29 04:21 UTC
It appears that when using `ToString()` to serialize a JSchema, dependencies held in a definition are not included in the string output. For example, using the following schema:

```json
[definitions, {
  "pants_size": {
    "type": "object",
    "properties": {
      "show_pants_size": {
        "type": "boolean",
        "default": false
      },
      "additionalProperties": false
    },
    "dependencies": {
      "pants_size": {
        "oneOf": [
          {
            "properties": {
              "show_pants_size": true,
              "size": {
                "type": "number"
              }
            },
            "required": [
              "size"
            ],
            "additionalProperties": false
          },
          {
            "properties": {
              "show_pants_size": false
            },
            "additionalProperties": false
          }
        ]
      }
    }
  }
}]
```
After calling `ToString()` the string representation of the object looks like this:
```json
"version": 12,
  "definitions": {
    "pants_size": {
      "type": "object",
      "properties": {
        "show_pants_size": {
          "type": "boolean",
          "default": false
        },
        "additionalProperties": false
      }
    }
  },
  "type": "object",
  "properties": {
    "mockProp": {
      "type": [
        "string",
        "null"
      ]
    },
    "shoe_size": {
      "type": "number",
      "minimum": 5.0,
      "maximum": 12.0,
      "multipleOf": 1.0
    },
    "pants_size": {
      "$ref": "#/definitions/pants_size"
    }
  },
  "required": [
    "mockProp"
  ]
}
```
I would expect the output to include the `dependencies` properties of the schema. Is this intended?

**Comment by JamesNK** [comment] 2019-08-29 06:22
```cs
[Test]
public void RoundtripJson()
{
    JSchema schema = JSchema.Parse(@"{
      ""definitions"": {
        ""pants_size"": {
          ""type"": ""object"",
          ""properties"": {
            ""show_pants_size"": {
              ""type"": ""boolean"",
              ""default"": false
            },
            ""additionalProperties"": false
          },
          ""dependencies"": {
            ""pants_size"": {
              ""oneOf"": [
                {
                  ""properties"": {
                    ""show_pants_size"": true,
                    ""size"": {
                      ""type"": ""number""
                    }
                  },
                  ""required"": [
                    ""size""
                  ],
                  ""additionalProperties"": false
                },
                {
                  ""properties"": {
                    ""show_pants_size"": false
                  },
                  ""additionalProperties"": false
                }
              ]
            }
          }
        }
      },
      ""oneOf"": [
        { ""$ref"": ""#/definitions/pants_size"" }
      ]
    }");

    string json = schema.ToString();
    Console.WriteLine(json);
}
```

Outputs:
```
{
  "definitions": {
    "pants_size": {
      "type": "object",
      "properties": {
        "show_pants_size": {
          "type": "boolean",
          "default": false
        },
        "additionalProperties": false
      },
      "dependencies": {
        "pants_size": {
          "oneOf": [
            {
              "additionalProperties": false,
              "properties": {
                "show_pants_size": true,
                "size": {
                  "type": "number"
                }
              },
              "required": [
                "size"
              ]
            },
            {
              "additionalProperties": false,
              "properties": {
                "show_pants_size": false
              }
            }
          ]
        }
      }
    }
  },
  "oneOf": [
    {
      "$ref": "#/definitions/pants_size"
    }
  ]
}
```

**Comment by anothercraig** [comment] 2019-08-29 07:04
Appreciate the quick reply, Mr. NK!

Here's another example of the definition/dependency usage which loses our inner `awesomeDefinitionProperty` property.

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "version": 1,
  "type": "object",
  "properties": {
    "awesomeProperty1": {
      "title": "awesomeProperty1",
      "$ref": "#/definitions/awesomeDefinition1"
    }
  },
  "definitions": {
    "awesomeDefinition1": {
      "title": "awesomeDefinition1",
      "type": "object",
      "properties": {
        "awesomeDefinitionProperty": {
          "title": "awesomeDefinitionProperty",
          "type": "boolean",
          "default": false
        }
      },
      "dependencies": {
        "awesomeDefinitionProperty": {
          "oneOf": [
            {
              "properties": {
                "awesomeDefinitionProperty": {
                  "enum": [
                    false
                  ]
                }
              }
            },
            {
              "properties": {
                "awesomeDefinitionProperty": {
                  "enum": [
                    true
                  ]
                },
                "checks": {
                  "title": "Checks",
                  "type": "object",
                  "properties": {
                    "Check1": {
                      "type": "boolean"
                    },
                    "Check2": {
                      "type": "boolean"
                    },
                    "Check3": {
                      "type": "boolean"
                    },
                    "Check4": {
                      "type": "boolean"
                    }
                  }
                },
                "additionalAwesomeProperty1": {
                  "title": "additionalAwesomeProperty1",
                  "$ref": "#/definitions/awesomeDefinition2"
                }
              }
            }
          ]
        }
      }
    },
    "awesomeDefinition2": {
      "type": "object",
      "properties": {
        "awesomeDefinition2Property": {
          "title": "awesomeDefinition2Property",
          "type": "boolean",
          "default": false
        }
      },
      "dependencies": {
        "awesomeDefinition2Property": {
          "oneOf": [
            {
              "properties": {
                "awesomeDefinition2Property": {
                  "enum": [
                    false
                  ]
                }
              }
            },
            {
              "properties": {
                "awesomeDefinition2Property": {
                  "enum": [
                    true
                  ]
                },
                "": {
                  "type": "string"
                }
              }
            }
          ]
        }
      }
    }
  }
}
```

Output:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "version": 1,
  "definitions": {
    "awesomeDefinition1": {
      "title": "awesomeDefinition1",
      "type": "object",
      "properties": {
        "awesomeDefinitionProperty": {
          "title": "awesomeDefinitionProperty",
          "type": "boolean",
          "default": false
        }
      }
    },
    "awesomeDefinition2": {
      "type": "object",
      "properties": {
        "awesomeDefinition2Property": {
          "title": "awesomeDefinition2Property",
          "type": "boolean",
          "default": false
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "awesomeProperty1": {
      "$ref": "#/definitions/awesomeDefinition1"
    }
  }
}
```

**Comment by valeriiudodov** [comment] 2019-08-29 23:33
From what I was able to determine is dependencies [got removed here](https://github.com/JamesNK/Newtonsoft.Json.Schema/blob/22eda750c124f2eda15bfb3a366cb010adc65384/Src/Newtonsoft.Json.Schema/Infrastructure/JSchemaWriter.cs#L153) when `token` is `definitions` object.

**Comment by JamesNK** [comment] 2019-08-29 23:39
I think this is a duplicate of https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/187

This has been fixed but not released yet.

**Comment by valeriiudodov** [comment] 2019-09-04 02:08
Thanks @JamesNK 
Has the new release been scheduled?

**Comment by JamesNK** [comment] 2019-09-08 09:24
A preview package is now on NuGet:  https://www.nuget.org/packages/Newtonsoft.Json.Schema/3.0.12-beta1 

This contains the dependency fix.

**Closed by JamesNK** 2019-09-08 09:24 UTC

**Comment by valeriiudodov** [comment] 2019-09-08 23:53
Much appreciated @JamesNK
