### ISSUE TITLE
Doesn't work in ASP.NET 5 on Linux

### ISSUE THREAD

**Issue by markrendle** [JamesNK/Newtonsoft.Json.Schema#4] opened 2015-02-02 17:19 UTC
When I try to load a schema from a file in an ASP.NET 5 on Linux using `File.OpenText` and `JsonTextReader`, I get MethodAccessExceptions against JsonReaderException.Create.

This is using `1.0.4` from NuGet via `kpm`.

What's really confusing is that, looking at the code, the conditions that are causing the exception shouldn't even be true, in that in my own code I can run this part:

```
if (reader.TokenType == JsonToken.None || reader.TokenType == JsonToken.Comment)
{
    if (!reader.Read())
        throw JsonReaderException.Create(reader, "Error reading schema from JsonReader.");
}

if (reader.TokenType != JsonToken.StartObject)
    throw JsonReaderException.Create(reader, "Unexpected token encountered when reading schema. Expected StartObject, got {0}.");
```

At the first go, obviously with a new JsonTextReader, `TokenType` is `None` so it does the read and then it's `StartObject`, so everything should be fine.

I've tried pulling the source for `Newtonsoft.Json` and `Newtonsoft.Json.Schema` into my project, but obviously that's just absolute hell and nothing works because it says it can't find `BigInteger`, `IXmlSerializable`, `SqlString` and just about every other type in the sodding BCL.

**Comment by JamesNK** [comment] 2015-02-02 19:26
They are both PCL rather than core projects.

I think the issue is that core is using an older version of json.net. Json.net ships with core and is used to load the project.json file, but that means it can't load the newer json.net version specified by the project file. This is a bug that needs to be fixed in core.

**Comment by markrendle** [comment] 2015-02-03 14:16
I've worked around this for the time being by pulling the source for both JSON.Net and Schema into my project, and adding these `frameworkAssemblies` in `project.json`:

```
    "frameworks": {
        "aspnet50": {
            "frameworkAssemblies": {
                "System.Runtime": "",
                "System.Runtime.Serialization": "",
                "System.Xml": "",
                "System.Xml.Linq": "",
                "System.Data": "",
                "System.Numerics": ""
            }
        }
    }
```

**Comment by JamesNK** [comment] 2015-06-27 12:29
Fixed in ASP.NET 5 Beta 5.

**Closed by JamesNK** 2015-06-27 12:29 UTC
